FROM nginx:latest

##To build image manually (without docker-compose) comment this line and unncomment the next
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
#COPY ./docker/bankendNinx/nginx.conf /etc/nginx/conf.d/default.conf
